service {
	cluster-name iotfleet
}

logging {
	console {
		context any info
	}
}

network {
	service {
		address any
		port 3000
	}

	heartbeat {
		mode mesh
		address local
		port 3002
		interval 150
		timeout 10
	}

	fabric {
		address local
		port 3001
	}
}

namespace iotfleet {
	replication-factor 1
	default-ttl 0
	nsup-period 120

	storage-engine device {
		file /opt/aerospike/data/iotfleet.dat
		filesize 4G
		read-page-cache true
	}
}

namespace secfleet {
	replication-factor 1
	default-ttl 0
	nsup-period 120

	storage-engine device {
		file /opt/aerospike/data/secfleet.dat
		filesize 4G
		read-page-cache true
	}
}
